/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package restassured.app;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;


public class MessageUtilsTest {
    @Test public void testGetMessage() {
        assertThat(1, is(1));
    }
}
